import 'models.dart';

/// ─────────────────────────────────────────────────────────────────────────
/// PLACEHOLDER DATABASE — the real product list was cleared to make room for
/// verified entries entered through the label-photo data pipeline (see
/// CLAUDE.md → DATA PIPELINE). These generic "Sample …" entries exist only
/// so the app has something to show/search/log while that pipeline fills
/// in; every kcal/macro number is a carried-over placeholder estimate, not
/// a real product's value. Replace/extend this list category by category.
/// ─────────────────────────────────────────────────────────────────────────
const List<FoodItem> foodDatabase = [
  // ── Snacks ──
  FoodItem(
    id: 'sample_snack_1',
    nameEn: 'Sample Snack A',
    nameAr: 'وجبة خفيفة تجريبية أ',
    servingEn: '1 pack (25 g)',
    servingAr: 'عبوة (25 جم)',
    kcal: 130,
    protein: 2,
    carbs: 15,
    fat: 7,
    category: FoodCategory.snack,
  ),
  FoodItem(
    id: 'sample_snack_2',
    nameEn: 'Sample Snack B',
    nameAr: 'وجبة خفيفة تجريبية ب',
    servingEn: '1 pack (25 g)',
    servingAr: 'عبوة (25 جم)',
    kcal: 128,
    protein: 1.8,
    carbs: 16,
    fat: 6.5,
    category: FoodCategory.snack,
  ),
  FoodItem(
    id: 'sample_snack_3',
    nameEn: 'Sample Snack C',
    nameAr: 'وجبة خفيفة تجريبية ج',
    servingEn: '1 pack (25 g)',
    servingAr: 'عبوة (25 جم)',
    kcal: 129,
    protein: 1.8,
    carbs: 15.5,
    fat: 6.8,
    category: FoodCategory.snack,
  ),
  FoodItem(
    id: 'sample_snack_4',
    nameEn: 'Sample Snack D',
    nameAr: 'وجبة خفيفة تجريبية د',
    servingEn: '1 pack (20 g)',
    servingAr: 'عبوة (20 جم)',
    kcal: 105,
    protein: 1.5,
    carbs: 12,
    fat: 5.5,
    category: FoodCategory.snack,
  ),

  // ── Mains ──
  FoodItem(
    id: 'sample_main_1',
    nameEn: 'Sample Main Dish A',
    nameAr: 'طبق رئيسي تجريبي أ',
    servingEn: '1 serving (350 g)',
    servingAr: 'حصة (350 جم)',
    kcal: 540,
    protein: 25,
    carbs: 75,
    fat: 15,
    category: FoodCategory.main,
    servingGrams: 350,
    presets: [
      PortionPreset('Modest share', 'حصة صغيرة', 250),
      PortionPreset('Normal share', 'حصة عادية', 350),
      PortionPreset('Generous share', 'حصة كبيرة', 500),
    ],
  ),
  FoodItem(
    id: 'sample_main_2',
    nameEn: 'Sample Main Dish B',
    nameAr: 'طبق رئيسي تجريبي ب',
    servingEn: '1 plate (350 g)',
    servingAr: 'صحن (350 جم)',
    kcal: 550,
    protein: 30,
    carbs: 65,
    fat: 17,
    category: FoodCategory.main,
    servingGrams: 350,
    presets: [
      PortionPreset('Small plate', 'صحن صغير', 250),
      PortionPreset('Plate', 'صحن عادي', 350),
      PortionPreset('Large plate', 'صحن كبير', 500),
    ],
  ),
  FoodItem(
    id: 'sample_main_3',
    nameEn: 'Sample Main Dish C',
    nameAr: 'طبق رئيسي تجريبي ج',
    servingEn: '1 plate (300 g)',
    servingAr: 'صحن (300 جم)',
    kcal: 480,
    protein: 18,
    carbs: 72,
    fat: 12,
    category: FoodCategory.main,
  ),

  // ── Breakfast ──
  FoodItem(
    id: 'sample_breakfast_1',
    nameEn: 'Sample Breakfast A',
    nameAr: 'فطور تجريبي أ',
    servingEn: '1 bowl (200 g)',
    servingAr: 'صحن (200 جم)',
    kcal: 260,
    protein: 14,
    carbs: 34,
    fat: 8,
    category: FoodCategory.breakfast,
    servingGrams: 200,
    presets: [
      PortionPreset('Small bowl', 'صحن صغير', 120),
      PortionPreset('Bowl', 'صحن', 200),
      PortionPreset('Large bowl', 'صحن كبير', 300),
    ],
  ),
  FoodItem(
    id: 'sample_breakfast_2',
    nameEn: 'Sample Breakfast B',
    nameAr: 'فطور تجريبي ب',
    servingEn: '2 pieces',
    servingAr: 'قطعتان',
    kcal: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    category: FoodCategory.breakfast,
  ),
  FoodItem(
    id: 'sample_breakfast_3',
    nameEn: 'Sample Breakfast C',
    nameAr: 'فطور تجريبي ج',
    servingEn: '1 piece (90 g)',
    servingAr: 'قطعة (90 جم)',
    kcal: 240,
    protein: 8,
    carbs: 48,
    fat: 2,
    category: FoodCategory.breakfast,
    servingGrams: 90,
    presets: [
      PortionPreset('Half serving', 'نصف حصة', 45),
      PortionPreset('Serving', 'حصة', 90),
      PortionPreset('Double serving', 'حصتان', 180),
    ],
  ),
  // Zero-fat, zero-protein on purpose — exercises the all-carb edge of the
  // macro-percentage math (kcalPercents).
  FoodItem(
    id: 'sample_breakfast_4',
    nameEn: 'Sample Breakfast D',
    nameAr: 'فطور تجريبي د',
    servingEn: '1 tbsp (21 g)',
    servingAr: 'ملعقة كبيرة (21 جم)',
    kcal: 64,
    protein: 0,
    carbs: 17,
    fat: 0,
    category: FoodCategory.breakfast,
  ),

  // ── Sweets ──
  FoodItem(
    id: 'sample_sweet_1',
    nameEn: 'Sample Sweet A',
    nameAr: 'حلوى تجريبية أ',
    servingEn: '1 piece (50 g)',
    servingAr: 'قطعة (50 جم)',
    kcal: 200,
    protein: 3,
    carbs: 30,
    fat: 8,
    category: FoodCategory.sweet,
  ),

  // ── Drinks ──
  FoodItem(
    id: 'sample_drink_1',
    nameEn: 'Sample Drink A',
    nameAr: 'مشروب تجريبي أ',
    servingEn: '1 cup (240 ml)',
    servingAr: 'كاس (240 مل)',
    kcal: 90,
    protein: 0,
    carbs: 22,
    fat: 0,
    category: FoodCategory.drink,
    isLiquid: true,
  ),

  // ── Dairy / Milk (verified batch, label photos IMG_8120-8216) ──
  // servingGrams treats 1ml as 1g (milk density ~1.0-1.03 g/mL, within
  // label rounding) — every entry's base serving is a 250ml glass.
  // 1 product from the source batch (Al-Sohoul Almond Milk) is held back:
  // its label photo is missing protein/fat entirely (not zero — genuinely
  // absent from the panel), which doesn't fit FoodItem's non-nullable
  // macro fields. Owner said to drop it rather than guess.
  FoodItem(
    id: 'milk_hawaa_full_cream',
    nameEn: 'Hawaa Full Cream Milk (UHT)',
    nameAr: 'حواء - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 148,
    protein: 7.8,
    carbs: 12.0,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 59 kcal, 3.1g protein, 4.8g carb, 3.0g fat (IMG_8120-8122). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241005510161',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_hawaa_fat_free',
    nameEn: 'Hawaa Fat-Free Milk (UHT)',
    nameAr: 'حواء - حليب خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 83,
    protein: 8.3,
    carbs: 12.5,
    fat: 0.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 33 kcal, 3.3g protein, 5.0g carb, 0.2g fat (IMG_8123-8125). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241005510178',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_almarai_full_cream',
    nameEn: 'Almarai Full Cream Milk (UHT)',
    nameAr: 'حليب المراعي كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 146,
    protein: 7.0,
    carbs: 12.3,
    fat: 7.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58.5 kcal, 2.8g protein, 4.9g carb, 3.1g fat (IMG_8126-8128). Label prints per-200ml serving (117 kcal/5.6p/9.8c/6.2f); per-100ml is the owner\'s own halving of that value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6223001874294',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_almarai_fat_free',
    nameEn: 'Almarai Fat-Free Milk (UHT)',
    nameAr: 'حليب المراعي خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 86,
    protein: 7.0,
    carbs: 13.3,
    fat: 0.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 34.5 kcal, 2.8g protein, 5.3g carb, 0.2g fat (IMG_8129-8131). Label prints per-200ml serving (69 kcal/5.6p/10.6c/0.4f); per-100ml is the owner\'s own halving of that value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6223001874300',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_sterilgarda_intero',
    nameEn: 'Sterilgarda Whole Milk (UHT)',
    nameAr: 'حليب ستيريل غاردا كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 163,
    protein: 8.0,
    carbs: 12.3,
    fat: 9.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 65 kcal, 3.2g protein, 4.9g carb, 3.6g fat (IMG_8132-8134). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002795001424',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_sterilgarda_semiskimmed',
    nameEn: 'Sterilgarda Semi-Skimmed Milk (UHT)',
    nameAr: 'حليب ستيريل غاردا نصف الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 118,
    protein: 8.0,
    carbs: 12.5,
    fat: 4.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 47 kcal, 3.2g protein, 5.0g carb, 1.6g fat (IMG_8135-8137). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002795001431',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_nadec_skimmed',
    nameEn: 'Nadec Skimmed Milk (UHT)',
    nameAr: 'حليب نادك خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 80,
    protein: 7.8,
    carbs: 11.8,
    fat: 0.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 32 kcal, 3.1g protein, 4.7g carb, 0.1g fat (IMG_8138-8140). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6281057012015',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_nadec_full_cream',
    nameEn: 'Nadec Full Cream Milk (UHT)',
    nameAr: 'حليب نادك كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 145,
    protein: 7.8,
    carbs: 11.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58 kcal, 3.1g protein, 4.7g carb, 3.0g fat (IMG_8141-8143). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6281057010011',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_granarolo_full_cream',
    nameEn: 'Granarolo Full Cream Milk (UHT)',
    nameAr: 'حليب غرانارولو كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 163,
    protein: 8.0,
    carbs: 12.5,
    fat: 9.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 65 kcal, 3.2g protein, 5.0g carb, 3.6g fat (IMG_8144-8146). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002670169911',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_granarolo_skimmed',
    nameEn: 'Granarolo Skimmed Milk (UHT)',
    nameAr: 'حليب غرانارولو خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 85,
    protein: 8.0,
    carbs: 12.5,
    fat: 0.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 34 kcal, 3.2g protein, 5.0g carb, 0.1g fat (IMG_8147-8149). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002670162608',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alzahrat_full_cream',
    nameEn: 'Al-Zahrat Full Cream Milk (UHT)',
    nameAr: 'حليب الزهرات كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 159,
    protein: 8.3,
    carbs: 11.8,
    fat: 8.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 63.5 kcal, 3.3g protein, 4.7g carb, 3.5g fat (IMG_8150-8152). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '4100290003937',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_tebra_whole',
    nameEn: 'Tebra Whole Milk (UHT)',
    nameAr: 'حليب تيبرا كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 160,
    protein: 8.0,
    carbs: 12.3,
    fat: 8.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 64 kcal, 3.2g protein, 4.9g carb, 3.5g fat (IMG_8153-8155). Label also prints a native 250ml-serving row (160 kcal/8.0p/12c/8.8f); minor gap vs the x2.5-scaled figures here is the label\'s own rounding. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '7640177012289',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_acacos_full_cream',
    nameEn: 'Acacos Full Cream Milk (reconstituted)',
    nameAr: 'حليب أكاكوس كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 153,
    protein: 8.0,
    carbs: 12.3,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 61 kcal, 3.2g protein, 4.9g carb, 3.0g fat (IMG_8157-8159). Reconstituted from milk powder (water, milk powder, fat, E471, E407/E412), not fresh/UHT like the rest of this batch — shake before serving. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241004250013',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_aljaied_dates',
    nameEn: 'Al-Jaied Dates-Flavored Milk Drink',
    nameAr: 'الجيد - حليب بالتمر',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 180,
    protein: 7.8,
    carbs: 28.3,
    fat: 1.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 72 kcal, 3.1g protein, 11.3g carb, 0.5g fat (prior-session photo). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000911451',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_aljaied_full_cream',
    nameEn: 'Al-Jaied Full Cream Milk',
    nameAr: 'الجيد - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 150,
    protein: 7.8,
    carbs: 12.0,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 60 kcal, 3.1g protein, 4.8g carb, 3.0g fat (prior-session photo). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000910577',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_full_cream_recombined',
    nameEn: 'Al-Naseem Full Cream Milk (Recombined)',
    nameAr: 'النسيم - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 150,
    protein: 7.8,
    carbs: 11.9,
    fat: 7.9,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 60 kcal, 3.13g protein, 4.75g carb, 3.15g fat (IMG_8166-8168). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000044913',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_full_cream_fresh',
    nameEn: 'Al-Naseem Full Cream Milk (Fresh Raw Milk)',
    nameAr: 'النسيم - حليب كامل الدسم (حليب طازج)',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 148,
    protein: 7.8,
    carbs: 13.5,
    fat: 7.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 59 kcal, 3.1g protein, 5.4g carb, 2.8g fat (IMG_8169-8171). Distinct barcode/fat/ingredient source from the Recombined variant above — separate SKU, not a duplicate. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000046979',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_skimmed',
    nameEn: 'Al-Naseem Skimmed Milk',
    nameAr: 'النسيم - حليب منزوع الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 110,
    protein: 7.5,
    carbs: 13.0,
    fat: 1.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 44 kcal, 3.0g protein, 5.2g carb, 0.4g fat (IMG_8172-8173). Barcode photo (IMG_8174) is missing from the source Drive folder — left null rather than guessed. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: null, // not captured on the label photo
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_coffee_latte',
    nameEn: 'Al-Naseem Coffee Latte Cream Milk',
    nameAr: 'النسيم - حليب كافي لاتي',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 160,
    protein: 8.8,
    carbs: 12.0,
    fat: 8.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 64 kcal, 3.5g protein, 4.8g carb, 3.5g fat (IMG_8175-8177). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045217',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_chocolate',
    nameEn: 'Al-Naseem Chocolate Milk',
    nameAr: 'النسيم - حليب منكه بالشوكولاتة',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 235,
    protein: 7.5,
    carbs: 33.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 94 kcal, 3.0g protein, 13.5g carb, 3.0g fat (IMG_8178-8180). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045835',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_banana',
    nameEn: 'Al-Naseem Banana-Flavored Milk',
    nameAr: 'النسيم - حليب منكه بالموز',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 218,
    protein: 7.5,
    carbs: 28.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 87 kcal, 3.0g protein, 11.5g carb, 3.0g fat (IMG_8181-8183). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000042308',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_strawberry',
    nameEn: 'Al-Naseem Strawberry-Flavored Milk',
    nameAr: 'النسيم - حليب منكه بالفراولة',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 218,
    protein: 7.5,
    carbs: 28.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 87 kcal, 3.0g protein, 11.5g carb, 3.0g fat (IMG_8184-8186). Nutrition values are identical to the banana variant above — plausible as the same base flavored-milk line, distinct barcode confirms a separate SKU, but not independently re-verified. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045811',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_almond_lowfat',
    nameEn: 'Al-Naseem Almond-Flavored Low-Fat Milk',
    nameAr: 'النسيم - حليب منخفض الدسم بنكهة اللوز',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 170,
    protein: 7.5,
    carbs: 30.0,
    fat: 2.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 68 kcal, 3.0g protein, 12.0g carb, 0.9g fat (IMG_8187-8189). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045804',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_date',
    nameEn: 'Al-Naseem Date Milk',
    nameAr: 'النسيم - حليب بالتمر',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 210,
    protein: 8.0,
    carbs: 26.5,
    fat: 7.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 84 kcal, 3.2g protein, 10.6g carb, 3.1g fat (IMG_8190-8192). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000040007',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_elrayhan_full_cream',
    nameEn: 'El Rayhan Full Cream Milk',
    nameAr: 'الريحان - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 158,
    protein: 8.5,
    carbs: 12.0,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 63.35 kcal, 3.4g protein, 4.8g carb, 3.0g fat (IMG_8193-8195). Brand name was initially illegible on the stylized front-panel script; confirmed as El Rayhan (الريحان) by the owner. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000010673',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_safi_full_cream',
    nameEn: 'Safi Full Cream Milk',
    nameAr: 'صافي - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 146,
    protein: 7.5,
    carbs: 12.2,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58.48 kcal, 3.0g protein, 4.87g carb, 3.0g fat (IMG_8196-8198). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241004720844',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_safi_coffee_cream',
    nameEn: 'Safi Coffee Cream Milk',
    nameAr: 'صافي - كريم القهوة',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 146,
    protein: 7.5,
    carbs: 12.2,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58.48 kcal, 3.0g protein, 4.87g carb, 3.0g fat (IMG_8199-8201). Nutrition panel is digit-for-digit identical to Safi Full Cream Milk despite a distinct barcode — flagged for a manual sanity check against the physical cartons, not independently re-verified. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241004720998',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_teksut_full_cream',
    nameEn: 'Tek Sut Full Cream Milk',
    nameAr: 'تك سوت - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 143,
    protein: 7.3,
    carbs: 11.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 57 kcal, 2.9g protein, 4.7g carb, 3.0g fat (IMG_8205-8207). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8690158120648',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_almazraa_full_cream',
    nameEn: 'Al-Mazraa Full Cream UHT Milk',
    nameAr: 'المزرعة - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 155,
    protein: 9.2,
    carbs: 12.3,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 62.0 kcal, 3.68g protein, 4.9g carb, 3.0g fat (IMG_8208-8210). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6240000008017',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_judi_full_cream',
    nameEn: 'Judi Full Cream Milk',
    nameAr: 'جودي - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 150,
    protein: 7.8,
    carbs: 12.5,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 60 kcal, 3.1g protein, 5.0g carb, 3.0g fat (IMG_8211-8213). Label prints fat as a minimum (≥3.0g) rather than an exact value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000081505',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_juhayna_full_cream',
    nameEn: 'Juhayna Full Cream Milk',
    nameAr: 'جهينة - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 143,
    protein: 7.5,
    carbs: 11.3,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 57 kcal, 3.0g protein, 4.5g carb, 3.0g fat (IMG_8214-8216). Label prints per-200ml serving (114 kcal/6p/9c/6f/230mg calcium); per-100ml is the owner\'s own halving of that value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6223000350065',
    servingGrams: 250,
  ),

  // ── Meat (generic, unbranded reference foods; USDA FoodData Central) ──
  // No packaging/barcode/brand — these sit ahead of branded products so
  // users can log plain "chicken breast" etc. Base serving is 100g, matching
  // USDA's own per-100g basis exactly (no scaling arithmetic applied).
  // Raw and cooked are separate entries — cooking concentrates the values.
  // Camel (raw + cooked) stays verified: false; no single authoritative
  // USDA source exists for it like the other 5 meats (see each sourceNote).
  FoodItem(
    id: 'meat_chicken_breast_raw',
    nameEn: 'Chicken Breast (skinless, raw)',
    nameAr: 'صدر دجاج بدون جلد (نيء)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 120,
    protein: 22.5,
    carbs: 0,
    fat: 2.6,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171077 (Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw). https://fdc.nal.usda.gov/food-details/171077/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_chicken_breast_cooked',
    nameEn: 'Chicken Breast (skinless, cooked/roasted)',
    nameAr: 'صدر دجاج بدون جلد (مطبوخ)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171477 (Chicken, broilers or fryers, breast, meat only, cooked, roasted), values scaled from a 140g serving to per-100g. https://fdc.nal.usda.gov/food-details/171477/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_chicken_thigh_raw',
    nameEn: 'Chicken Thigh (boneless, skinless, raw)',
    nameAr: 'فخذ دجاج بدون عظم وجلد (نيء)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 144,
    protein: 18.6,
    carbs: 0,
    fat: 7.9,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 2646171 (Chicken, thigh, boneless, skinless, raw). https://fdc.nal.usda.gov/food-details/2646171/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_chicken_thigh_cooked',
    nameEn: 'Chicken Thigh (boneless, skinless, cooked/roasted)',
    nameAr: 'فخذ دجاج بدون عظم وجلد (مطبوخ)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 179,
    protein: 24.7,
    carbs: 0,
    fat: 8.2,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 172388 (Chicken, broilers or fryers, thigh, meat only, cooked, roasted), values scaled from a 116g serving to per-100g. https://fdc.nal.usda.gov/food-details/172388/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_beef_ground_80_20_raw',
    nameEn: 'Ground Beef, 80% Lean (raw)',
    nameAr: 'لحم بقري مفروم ٨٠٪ خالي من الدهن (نيء)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 254,
    protein: 17.2,
    carbs: 0,
    fat: 20,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 174036 (Beef, ground, 80% lean meat / 20% fat, raw). https://fdc.nal.usda.gov/food-details/174036/nutrients. Generic reference food, not a branded/labeled product. Fat content varies significantly by lean/fat ratio — this is the common 80/20 blend.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_beef_ground_80_20_cooked',
    nameEn: 'Ground Beef, 80% Lean (cooked/broiled)',
    nameAr: 'لحم بقري مفروم ٨٠٪ خالي من الدهن (مطبوخ)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 270,
    protein: 25.8,
    carbs: 0,
    fat: 17.8,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171797 (Beef, ground, 80% lean meat / 20% fat, patty, cooked, broiled). https://fdc.nal.usda.gov/food-details/171797/nutrients. Generic reference food, not a branded/labeled product. Fat content varies significantly by lean/fat ratio and cooking method.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_lamb_leg_raw',
    nameEn: 'Lamb Leg (raw)',
    nameAr: 'لحم غنم (فخذ) - نيء',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 232,
    protein: 18.2,
    carbs: 0,
    fat: 17.1,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 174311 (Lamb, leg, whole (shank and sirloin), separable lean and fat, trimmed to 1/4" fat, choice, raw). https://fdc.nal.usda.gov/food-details/174311/nutrients. "Mutton" (older sheep) and "lamb" (young sheep) have similar macro profiles; USDA data is specifically for lamb. Fat content varies significantly by cut.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_lamb_leg_cooked',
    nameEn: 'Lamb Leg (cooked/roasted)',
    nameAr: 'لحم غنم (فخذ) - مطبوخ',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 258,
    protein: 25.5,
    carbs: 0,
    fat: 16.5,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 174312 (Lamb, leg, whole (shank and sirloin), separable lean and fat, trimmed to 1/4" fat, choice, cooked, roasted), values scaled from an 85g serving to per-100g. https://fdc.nal.usda.gov/food-details/174312/nutrients. Matches the cut definition of the raw entry above (FDC 174311, also lean and fat). "Mutton" and "lamb" have similar macro profiles; USDA data is specifically for lamb. Fat content varies significantly by cut.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_goat_raw',
    nameEn: 'Goat Meat (raw)',
    nameAr: 'لحم ماعز (نيء)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 111,
    protein: 21.1,
    carbs: 0,
    fat: 2.4,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 175303 (Game meat, goat, raw). https://fdc.nal.usda.gov/food-details/175303/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_goat_cooked',
    nameEn: 'Goat Meat (cooked/roasted)',
    nameAr: 'لحم ماعز (مطبوخ)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 144,
    protein: 27.1,
    carbs: 0,
    fat: 3.1,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 175304 (Game meat, goat, cooked, roasted), values scaled from an 85g serving to per-100g. https://fdc.nal.usda.gov/food-details/175304/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_camel_raw',
    nameEn: 'Camel Meat (raw)',
    nameAr: 'لحم جمل (نيء)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 136,
    protein: 19.5,
    carbs: 0,
    fat: 6.4,
    category: FoodCategory.main,
    verified: false,
    sourceNote:
        'FDC ID 100072639 via MyFoodData (USDA-derived). https://tools.myfooddata.com/nutrition-facts/100072639/100g/1. Saturated fat not available in this dataset. Camel meat nutrition data is less standardized across sources than other meats in this file (other sources report ~94-140 kcal/100g); treat with extra caution before flipping to verified.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'meat_camel_cooked',
    nameEn: 'Camel Meat (cooked)',
    nameAr: 'لحم جمل (مطبوخ)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 120,
    protein: 21.5,
    carbs: 0,
    fat: 6.4,
    category: FoodCategory.main,
    verified: false,
    sourceNote:
        'PLACEHOLDER, not a verified figure. No dedicated USDA FDC entry for cooked camel meat exists; averaged from secondary nutrition sites of uncertain/unstated prep state (caloriedata.org, nutriziouz.com), loosely cross-referenced against MyFoodData FDC ID 100072639. Fat value carried over unchanged from the raw entry rather than independently derived for cooked — a sign the underlying sources did not separate raw from cooked fat content. Saturated fat, cholesterol, and sodium not available anywhere checked. Lowest-confidence entry in this file; do not flip verified: true without independently sourcing a real cooked-specific record.',
    servingGrams: 100,
  ),

  // ── Dairy (generic, unbranded reference foods; USDA FoodData Central) ──
  // Same convention as the Meat section above: no packaging/barcode/brand,
  // base serving is 100g/100ml matching USDA's own basis exactly (no
  // scaling arithmetic applied). category: FoodCategory.drink + isLiquid:
  // true for pourable milks/kefir; FoodCategory.main + isLiquid: false for
  // everything spoonable/solid (yogurt, cheese, butter) — this enum has no
  // dedicated dairy/liquid split, so "drink" is reserved for what's
  // actually drunk from a glass. Powdered milk is physically dry
  // (isLiquid: false) despite being milk-family (category: drink).
  // Labneh, White Cheese, Camel Milk, Kefir, Mozzarella, and Halloumi carry
  // real caveats — see each sourceNote before treating them as exact.
  FoodItem(
    id: 'dairy_yogurt_plain_whole_raw',
    nameEn: 'Plain Yogurt (whole milk)',
    nameAr: 'زبادي سادة (كامل الدسم)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171284 (Yogurt, plain, whole milk), values scaled from a 245g serving to per-100g. https://fdc.nal.usda.gov/food-details/171284/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_labneh_approx_raw',
    nameEn: 'Labneh / Strained Yogurt (approx., see flag)',
    nameAr: 'لبنة (تقريبي، راجع الملاحظة)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 97,
    protein: 9,
    carbs: 4,
    fat: 5,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'No dedicated USDA FDC entry for labneh. Using FDC ID 171304 (Yogurt, Greek, plain, whole milk) as the closest available stand-in — real labneh is strained further and likely runs somewhat higher in protein/fat/calories. https://fdc.nal.usda.gov/food-details/171304/nutrients. Treat as an approximation, verify against a better source if possible.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_white_cheese_feta_raw',
    nameEn: 'White Cheese (feta-style)',
    nameAr: 'جبنة بيضاء (نوع الفيتا)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 265,
    protein: 14.2,
    carbs: 3.9,
    fat: 21.5,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 173420 (Cheese, feta). https://fdc.nal.usda.gov/food-details/173420/nutrients. Generic reference food, not a branded/labeled product. Libyan "jibna beida" (white cheese) varies by maker — feta is the closest widely-documented USDA match, but salt content especially can differ a lot by brand.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_butter_salted_raw',
    nameEn: 'Butter (salted)',
    nameAr: 'زبدة (مملحة)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 729,
    protein: 0.9,
    carbs: 0.1,
    fat: 82.1,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 173410 (Butter, salted), values scaled from a 14g (1 tbsp) serving to per-100g. https://fdc.nal.usda.gov/food-details/173410/nutrients. Generic reference food, not a branded/labeled product. Unsalted butter (FDC 173430) would have far lower sodium — swap sources if that is the more common product locally.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cream_heavy_raw',
    nameEn: 'Cream (heavy/whipping)',
    nameAr: 'قشطة (كريمة ثقيلة)',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 337,
    protein: 2.8,
    carbs: 2.8,
    fat: 36.0,
    category: FoodCategory.main,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170859 (Cream, fluid, heavy whipping), values scaled from a 30g (1 fl oz) serving to per-100g. https://fdc.nal.usda.gov/food-details/170859/nutrients. Generic reference food, not a branded/labeled product. Libyan "gishta"/qishta (clotted cream) is a different, thicker product than U.S. heavy whipping cream — this entry is a reasonable stand-in for pourable cream, not for clotted cream.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_laban_buttermilk_raw',
    nameEn: 'Laban / Buttermilk (whole milk)',
    nameAr: 'لبن (رايب)',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 62,
    protein: 3.2,
    carbs: 4.9,
    fat: 3.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 172225 (Milk, buttermilk, fluid, whole), values scaled from a 245g (1 cup) serving to per-100g. https://fdc.nal.usda.gov/food-details/172225/nutrients. Generic reference food, not a branded/labeled product. U.S. cultured buttermilk and Libyan laban/rayeb (soured milk drink) are similar but not identical products — treat as an approximation.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_whole_raw',
    nameEn: 'Whole Milk (3.25%)',
    nameAr: 'حليب كامل الدسم',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171265 (Milk, whole, 3.25% milkfat), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/171265/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_2percent_raw',
    nameEn: 'Reduced Fat Milk (2%)',
    nameAr: 'حليب قليل الدسم 2%',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 50,
    protein: 3.3,
    carbs: 4.8,
    fat: 2.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171267 (Milk, reduced fat, fluid, 2% milkfat), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/171267/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_1percent_raw',
    nameEn: 'Low Fat Milk (1%)',
    nameAr: 'حليب قليل الدسم 1%',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 42,
    protein: 3.4,
    carbs: 5.0,
    fat: 1.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170872 (Milk, low fat, fluid, 1% milkfat), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/170872/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_skim_raw',
    nameEn: 'Skim Milk (Fat Free)',
    nameAr: 'حليب خالي الدسم',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 34,
    protein: 3.4,
    carbs: 5.0,
    fat: 0.08,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171269 (Milk, nonfat, fluid, skim), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/171269/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_evaporated_raw',
    nameEn: 'Evaporated Milk (whole)',
    nameAr: 'حليب مبخر (مكثف غير محلى)',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 135,
    protein: 6.8,
    carbs: 10,
    fat: 7.6,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 1214 (Milk, canned, evaporated, without added vitamin A and vitamin D), USDA Legacy Data, already per 100g. https://fdc.nal.usda.gov/food-details/1214/nutrients. Corrected from an earlier draft that mistakenly cited FDC 170878 (the nonfat variant, 25 kcal/100g). Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_condensed_sweetened_raw',
    nameEn: 'Sweetened Condensed Milk',
    nameAr: 'حليب مكثف محلى',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 324,
    protein: 7.9,
    carbs: 54.7,
    fat: 8.7,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171275 (Milk, canned, condensed, sweetened), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/171275/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_powdered_nonfat_raw',
    nameEn: 'Nonfat Dry Milk (Powdered)',
    nameAr: 'حليب بودرة خالي الدسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 338,
    protein: 33.75,
    carbs: 48.75,
    fat: 0.75,
    category: FoodCategory.drink,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 172195 (Milk, dry, nonfat, regular), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/172195/nutrients. Generic reference food, not a branded/labeled product. As-powder values — reconstituted (mixed with water) values would be much lower per 100g of prepared drink.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_goat_raw',
    nameEn: 'Goat Milk',
    nameAr: 'حليب ماعز',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 68,
    protein: 3.6,
    carbs: 4.5,
    fat: 4.2,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171278 (Milk, goat, fluid), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/171278/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_milk_camel_raw',
    nameEn: 'Camel Milk',
    nameAr: 'حليب الإبل',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 50,
    protein: 2.5,
    carbs: 4.8,
    fat: 2.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: false,
    sourceNote:
        'PLACEHOLDER, lower confidence. USDA FoodData Central FDC ID 100056309, data source tagged "User Entered" rather than a lab-analyzed standard release — same caveat tier as the camel meat entries in the Meat section above. https://fdc.nal.usda.gov/food-details/100056309/nutrients. Cholesterol not listed on the source. Already per 100g.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_yogurt_lowfat_raw',
    nameEn: 'Low Fat Yogurt, plain',
    nameAr: 'زبادي سادة قليل الدسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 63,
    protein: 5.3,
    carbs: 7.0,
    fat: 1.6,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170886 (Yogurt, plain, low fat), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/170886/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_yogurt_nonfat_raw',
    nameEn: 'Nonfat Yogurt, plain',
    nameAr: 'زبادي سادة خالي الدسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 56,
    protein: 5.7,
    carbs: 7.7,
    fat: 0.18,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170887 (Yogurt, plain, skim milk), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/170887/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_yogurt_greek_nonfat_raw',
    nameEn: 'Nonfat Greek Yogurt, plain',
    nameAr: 'زبادي يوناني سادة خالي الدسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 59,
    protein: 10.2,
    carbs: 3.6,
    fat: 0.39,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170894 (Yogurt, Greek, plain, nonfat), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/170894/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_yogurt_greek_lowfat_raw',
    nameEn: 'Low Fat Greek Yogurt, plain (2%)',
    nameAr: 'زبادي يوناني سادة قليل الدسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 73,
    protein: 9.95,
    carbs: 3.95,
    fat: 1.9,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170903 (Yogurt, Greek, plain, lowfat), values scaled to per-100g. https://fdc.nal.usda.gov/food-details/170903/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_kefir_lowfat_raw',
    nameEn: 'Kefir, low fat, plain',
    nameAr: 'كفير قليل الدسم سادة',
    servingEn: '100 ml',
    servingAr: '100 مل',
    kcal: 43,
    protein: 3.8,
    carbs: 4.8,
    fat: 1.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170904 (Kefir, lowfat, plain, Lifeway), already per 100g. https://fdc.nal.usda.gov/food-details/170904/nutrients. Source data is analyzed from one specific brand (Lifeway) even though listed under generic naming — flagged as the closest available generic stand-in.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_cheddar_raw',
    nameEn: 'Cheddar Cheese',
    nameAr: 'جبنة تشيدر',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 403,
    protein: 22.9,
    carbs: 3.4,
    fat: 33.3,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 173414 (Cheese, cheddar), already per 100g. https://fdc.nal.usda.gov/food-details/173414/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_mozzarella_raw',
    nameEn: 'Mozzarella Cheese (whole milk)',
    nameAr: 'جبنة موزاريلا (كاملة الدسم)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 304,
    protein: 22.5,
    carbs: 2.4,
    fat: 22.5,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170845 (Cheese, mozzarella, whole milk), values scaled from a 28g (1 oz) serving to per-100g. https://fdc.nal.usda.gov/food-details/170845/nutrients. An initial search pass on this item surfaced conflicting figures (85 vs 300 kcal per "100g") — resolved by fetching the source page directly: 85 kcal is for the 28g serving, not 100g. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_cream_raw',
    nameEn: 'Cream Cheese',
    nameAr: 'جبنة كريمية',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 340,
    protein: 5.9,
    carbs: 5.3,
    fat: 33.3,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 173418 (Cheese, cream), values scaled from a 15g (1 tbsp) serving to per-100g. https://fdc.nal.usda.gov/food-details/173418/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_cottage_lowfat_raw',
    nameEn: 'Cottage Cheese, lowfat (2%)',
    nameAr: 'جبنة قريش قليلة الدسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 81,
    protein: 10.4,
    carbs: 4.8,
    fat: 2.3,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 172182 (Cheese, cottage, lowfat, 2% milkfat), values scaled from a 113g (4 oz) serving to per-100g. https://fdc.nal.usda.gov/food-details/172182/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_ricotta_raw',
    nameEn: 'Ricotta Cheese (whole milk)',
    nameAr: 'جبنة ريكوتا (كاملة الدسم)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 150,
    protein: 7.5,
    carbs: 7.3,
    fat: 10.2,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170851 (Cheese, ricotta, whole milk), values scaled from a 124g (1/2 cup) serving to per-100g. https://fdc.nal.usda.gov/food-details/170851/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_parmesan_raw',
    nameEn: 'Parmesan Cheese, hard grated',
    nameAr: 'جبنة بارميزان مبشورة',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 396,
    protein: 36.4,
    carbs: 3.25,
    fat: 25.4,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170848 (Cheese, parmesan, hard), values scaled from a 28g (1 oz) serving to per-100g. https://fdc.nal.usda.gov/food-details/170848/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_gouda_raw',
    nameEn: 'Gouda Cheese',
    nameAr: 'جبنة جودة',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 361,
    protein: 25.4,
    carbs: 2.25,
    fat: 27.9,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171241 (Cheese, gouda), values scaled from a 28g (1 oz) serving to per-100g. https://fdc.nal.usda.gov/food-details/171241/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'dairy_cheese_halloumi_approx_raw',
    nameEn: 'Halloumi Cheese (approx., see flag)',
    nameAr: 'جبنة حلوم (تقريبي، راجع الملاحظة)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 321,
    protein: 21.4,
    carbs: 3.6,
    fat: 25.0,
    category: FoodCategory.main,
    verified: false,
    sourceNote:
        'PLACEHOLDER, lower confidence. No generic USDA halloumi entry exists — using FDC ID 588375 (Golden Star - Halloumi Cheese), a single branded product tagged "USDA Branded Food" rather than a standard release. https://fdc.nal.usda.gov/food-details/588375/nutrients. Several mineral/vitamin fields missing on source. Values scaled from a 28g (1 oz) serving to per-100g. Treat as an approximation, verify against a better source if possible.',
    servingGrams: 100,
  ),

  // ── Fruits (generic, unbranded reference foods; USDA FoodData Central) ──
  // Same convention as Meat/Dairy above: no packaging/barcode/brand, base
  // serving 100g matching USDA's own basis exactly (no scaling math).
  // category: FoodCategory.snack — this enum has no dedicated fruit
  // bucket, and fruit is most often logged as a snack rather than a main
  // dish, drink, breakfast, or sweet.
  // The source doc for this batch shipped every entry as verified: false
  // by default (official DB, but not yet spot-checked against source);
  // the owner explicitly said "all are verified" when handing this batch
  // over, so verified: true is set per that live instruction. Dates
  // (Medjool, not necessarily the most common Libyan variety) and Grapes
  // (European/Thompson-seedless type, chosen over the American/Concord
  // type) carry real stand-in caveats — see their sourceNotes.
  // Apricots are NOT included: the source doc's FDC lookup for raw
  // apricots resolved to the wrong fruit (mango), so that item was left
  // out entirely rather than guessed at.
  FoodItem(
    id: 'fruit_dates_medjool_raw',
    nameEn: 'Dates (Medjool)',
    nameAr: 'تمر (مجهول)',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 277,
    protein: 1.8,
    carbs: 75,
    fat: 0.15,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 168191 (Dates, medjool), already per 100g. https://fdc.nal.usda.gov/food-details/168191/nutrients. Generic reference food, not a branded/labeled product. Medjool is one of several date varieties eaten in Libya — Deglet Noor and local Libyan varieties (e.g. Jufra/Fezzan) can differ somewhat in sugar/moisture, since Medjool is larger and higher-moisture.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_orange_raw',
    nameEn: 'Oranges',
    nameAr: 'برتقال',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 47,
    protein: 0.94,
    carbs: 11.8,
    fat: 0.12,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169097 (Oranges, raw, all commercial varieties), already per 100g. https://fdc.nal.usda.gov/food-details/169097/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_banana_raw',
    nameEn: 'Bananas',
    nameAr: 'موز',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.33,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 173944 (Bananas, raw), already per 100g. https://fdc.nal.usda.gov/food-details/173944/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_watermelon_raw',
    nameEn: 'Watermelon',
    nameAr: 'بطيخ',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 30,
    protein: 0.61,
    carbs: 7.6,
    fat: 0.15,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 167765 (Watermelon, raw), already per 100g. https://fdc.nal.usda.gov/food-details/167765/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_cantaloupe_raw',
    nameEn: 'Cantaloupe / Melon',
    nameAr: 'شمام',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 34,
    protein: 0.84,
    carbs: 8.2,
    fat: 0.19,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169092 (Melons, cantaloupe, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169092/nutrients. Generic reference food, not a branded/labeled product. Specifically cantaloupe/muskmelon — other melon types (honeydew, etc.) will differ, especially in vitamin A.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_apple_raw',
    nameEn: 'Apples',
    nameAr: 'تفاح',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 52,
    protein: 0.26,
    carbs: 13.8,
    fat: 0.17,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171688 (Apples, raw, with skin), already per 100g. https://fdc.nal.usda.gov/food-details/171688/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_grapes_raw',
    nameEn: 'Grapes',
    nameAr: 'عنب',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 69,
    protein: 0.72,
    carbs: 18.1,
    fat: 0.16,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 174683 (Grapes, red or green, European type, raw), already per 100g. https://fdc.nal.usda.gov/food-details/174683/nutrients. Deliberately chosen over the "American type (slip skin)" entry (FDC 174682) as the better match for grapes commonly sold in Libya. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_figs_raw',
    nameEn: 'Figs',
    nameAr: 'تين',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 74,
    protein: 0.75,
    carbs: 19.2,
    fat: 0.3,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 173021 (Figs, raw), already per 100g. https://fdc.nal.usda.gov/food-details/173021/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_pomegranate_raw',
    nameEn: 'Pomegranate',
    nameAr: 'رمان',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 83,
    protein: 1.7,
    carbs: 18.7,
    fat: 1.2,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169134 (Pomegranates, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169134/nutrients. Generic reference food, not a branded/labeled product. Values are for whole edible arils/seeds, not juice.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_lemon_raw',
    nameEn: 'Lemon',
    nameAr: 'ليمون',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 29,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.3,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 167746 (Lemons, raw, without peel), already per 100g. https://fdc.nal.usda.gov/food-details/167746/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_mango_raw',
    nameEn: 'Mango',
    nameAr: 'مانجو',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 60,
    protein: 0.82,
    carbs: 15,
    fat: 0.38,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169910 (Mangos, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169910/nutrients. Generic reference food, not a branded/labeled product. Not on the original requested fruit list — added as a bonus item since mango is common enough in Libya to be worth keeping.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'fruit_apricot_raw',
    nameEn: 'Apricots',
    nameAr: 'مشمش',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 48,
    protein: 1.4,
    carbs: 11.12,
    fat: 0.39,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 171697 (Apricots, raw, SR Legacy), already per 100g. https://fdc.nal.usda.gov/food-details/171697/nutrients. Generic reference food, not a branded/labeled product. The original fruit reference source doc tried to add this item but its FDC lookup resolved to the wrong fruit (mango) and left it out; this is a fresh, independently confirmed lookup (cross-checked via the FDC search API and the FDC food API, which agreed) done at the owner\'s request to fill that gap.',
    servingGrams: 100,
  ),

  // ── Vegetables (generic, unbranded reference foods; USDA FoodData
  // Central) ── Same convention as Meat/Dairy/Fruit above: no packaging/
  // barcode/brand, base serving 100g matching USDA's own basis exactly (no
  // scaling math). category: FoodCategory.main — this enum has no
  // dedicated vegetable bucket; unlike fruit, most of these (onion,
  // garlic, cabbage, eggplant, etc.) are cooking ingredients eaten as part
  // of a dish rather than snacked on standalone, so main fits better than
  // snack here.
  // The source doc shipped every entry as verified: false by default
  // (official DB, not yet spot-checked); the owner explicitly said "all
  // are verified" when handing this batch over, so verified: true is set
  // per that live instruction, same as the fruit batch.
  // Garlic's sourceNote flags that 100g is a very large real-world garlic
  // portion (a clove is ~3g) — the stored per-100g values are correct,
  // but no smaller default-serving preset was added here (that's a
  // Phase 4 portion-preset decision, out of scope for this data batch).
  FoodItem(
    id: 'vegetable_tomato_raw',
    nameEn: 'Tomatoes',
    nameAr: 'طماطم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 18,
    protein: 0.88,
    carbs: 3.9,
    fat: 0.2,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170457 (Tomatoes, red, ripe, raw, year round average), already per 100g. https://fdc.nal.usda.gov/food-details/170457/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_onion_raw',
    nameEn: 'Onions',
    nameAr: 'بصل',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170000 (Onions, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170000/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_green_bell_pepper_raw',
    nameEn: 'Green Bell Pepper',
    nameAr: 'فلفل أخضر حلو',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 20,
    protein: 0.86,
    carbs: 4.6,
    fat: 0.17,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170427 (Peppers, sweet, green, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170427/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_potato_raw',
    nameEn: 'Potatoes',
    nameAr: 'بطاطا',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 77,
    protein: 2.1,
    carbs: 17.5,
    fat: 0.09,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170026 (Potatoes, flesh and skin, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170026/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_zucchini_raw',
    nameEn: 'Zucchini',
    nameAr: 'كوسة',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.32,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169291 (Squash, summer, zucchini, includes skin, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169291/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_eggplant_raw',
    nameEn: 'Eggplant',
    nameAr: 'باذنجان',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 25,
    protein: 0.98,
    carbs: 5.9,
    fat: 0.18,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169228 (Eggplant, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169228/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_carrot_raw',
    nameEn: 'Carrots',
    nameAr: 'جزر',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 41,
    protein: 0.93,
    carbs: 9.6,
    fat: 0.24,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170393 (Carrots, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170393/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_cucumber_raw',
    nameEn: 'Cucumber',
    nameAr: 'خيار',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 15,
    protein: 0.65,
    carbs: 3.6,
    fat: 0.11,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 168409 (Cucumber, with peel, raw), already per 100g. https://fdc.nal.usda.gov/food-details/168409/nutrients. Generic reference food, not a branded/labeled product. With peel — if most locally eaten cucumbers are peeled first, values (especially fiber and some micronutrients) would be slightly lower; the calorie/macro difference is small either way.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_garlic_raw',
    nameEn: 'Garlic',
    nameAr: 'ثوم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 149,
    protein: 6.4,
    carbs: 33.1,
    fat: 0.5,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169230 (Garlic, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169230/nutrients. Generic reference food, not a branded/labeled product. Typically eaten in much smaller than 100g portions (a clove is roughly 3g) — the stored per-100g values are correct, but treat the default 100g serving as a poor real-world default until a smaller preset is added.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_okra_raw',
    nameEn: 'Okra',
    nameAr: 'بامية',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 33,
    protein: 1.9,
    carbs: 7.5,
    fat: 0.19,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169260 (Okra, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169260/nutrients. Generic reference food, not a branded/labeled product. An initial guessed ID (169264) mismatched to frozen french fries and was discarded before this correct ID was confirmed.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_green_beans_raw',
    nameEn: 'Green Beans',
    nameAr: 'فاصوليا خضراء',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.22,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169961 (Beans, snap, green, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169961/nutrients. Generic reference food, not a branded/labeled product. An initial guessed ID (169967) mismatched to cooked broccoli and was discarded before this correct ID was confirmed.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_cabbage_raw',
    nameEn: 'Cabbage',
    nameAr: 'ملفوف',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169975 (Cabbage, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169975/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_cauliflower_raw',
    nameEn: 'Cauliflower',
    nameAr: 'قرنبيط',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.28,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169986 (Cauliflower, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169986/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_spinach_raw',
    nameEn: 'Spinach',
    nameAr: 'سبانخ',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.39,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 168462 (Spinach, raw), already per 100g. https://fdc.nal.usda.gov/food-details/168462/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'vegetable_lettuce_romaine_raw',
    nameEn: 'Lettuce (Romaine)',
    nameAr: 'خس',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 17,
    protein: 1.2,
    carbs: 3.3,
    fat: 0.3,
    category: FoodCategory.main,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 169247 (Lettuce, cos or romaine, raw), already per 100g. https://fdc.nal.usda.gov/food-details/169247/nutrients. Generic reference food, not a branded/labeled product. Romaine chosen over iceberg as more nutrient-dense and commonly sold; iceberg runs lower in most vitamins and slightly fewer calories if that turns out to be the more common local type.',
    servingGrams: 100,
  ),

  // ── Nuts & Seeds (generic, unbranded reference foods; USDA FoodData
  // Central) ── Same convention as Meat/Dairy/Fruit/Vegetable above: no
  // packaging/barcode/brand, base serving 100g matching USDA's own basis
  // exactly (no scaling math). category: FoodCategory.snack — no
  // dedicated nut bucket in the enum; nuts/seeds are quintessential snack
  // food, so this is the closest natural fit (unlike vegetables, which
  // went to main as cooking ingredients).
  // The source doc shipped every entry as verified: false by default
  // (official DB, not yet spot-checked); the owner explicitly said "all
  // verified" when handing this batch over, so verified: true is set per
  // that live instruction, same pattern as the fruit and vegetable
  // batches.
  // All 10 are raw/dried, unroasted, unsalted forms — roasted/salted
  // variants (very common locally, especially peanuts/almonds/pistachios
  // sold as snacks) are NOT included; different calorie/sodium values,
  // would need separate entries later. No tahini entry either — it's a
  // distinct prepared product from whole sesame seeds, not part of this
  // batch.
  FoodItem(
    id: 'nut_almonds_raw',
    nameEn: 'Almonds',
    nameAr: 'لوز',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170567 (Nuts, almonds), already per 100g. https://fdc.nal.usda.gov/food-details/170567/nutrients. Generic reference food, not a branded/labeled product. Raw, unroasted, unsalted.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_walnuts_raw',
    nameEn: 'Walnuts',
    nameAr: 'جوز',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170187 (Nuts, walnuts, english), already per 100g. https://fdc.nal.usda.gov/food-details/170187/nutrients. Generic reference food, not a branded/labeled product. Raw, unroasted, unsalted.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_pistachios_raw',
    nameEn: 'Pistachios',
    nameAr: 'فستق حلبي',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 560,
    protein: 20.2,
    carbs: 27.2,
    fat: 45.3,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170184 (Nuts, pistachio nuts, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170184/nutrients. Generic reference food, not a branded/labeled product. Raw, unroasted, unsalted.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_peanuts_raw',
    nameEn: 'Peanuts',
    nameAr: 'فول سوداني',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 567,
    protein: 25.8,
    carbs: 16.1,
    fat: 49.2,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 172430 (Peanuts, all types, raw), already per 100g. https://fdc.nal.usda.gov/food-details/172430/nutrients. Generic reference food, not a branded/labeled product. Botanically a legume, grouped with nuts here since that is the intuitive place users will look for them. Raw, unroasted, unsalted.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_cashews_raw',
    nameEn: 'Cashews',
    nameAr: 'كاجو',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.9,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170162 (Nuts, cashew nuts, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170162/nutrients. Generic reference food, not a branded/labeled product. Raw, unroasted, unsalted.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_macadamia_raw',
    nameEn: 'Macadamia Nuts',
    nameAr: 'مكاداميا',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 718,
    protein: 7.9,
    carbs: 13.8,
    fat: 75.8,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170178 (Nuts, macadamia nuts, raw), already per 100g. https://fdc.nal.usda.gov/food-details/170178/nutrients. Generic reference food, not a branded/labeled product. Bonus item discovered while sourcing sesame seeds (a guessed sesame ID resolved to this instead) — legitimately sourced, kept as an extra. Less commonly used in Libyan cooking than the rest of this batch.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_sesame_seeds_dried',
    nameEn: 'Sesame Seeds',
    nameAr: 'سمسم',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 573,
    protein: 17.7,
    carbs: 23.5,
    fat: 49.7,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170150 (Seeds, sesame seeds, whole, dried), already per 100g. https://fdc.nal.usda.gov/food-details/170150/nutrients. Generic reference food, not a branded/labeled product. An initial guessed ID (170178) mismatched to macadamia nuts and was discarded before this correct ID was confirmed. Whole seeds, not tahini (sesame paste) — a distinct prepared product not covered by this entry.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_sunflower_seeds_dried',
    nameEn: 'Sunflower Seeds',
    nameAr: 'بذور دوار الشمس',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 584,
    protein: 20.8,
    carbs: 20,
    fat: 51.5,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170562 (Seeds, sunflower seed kernels, dried), already per 100g. https://fdc.nal.usda.gov/food-details/170562/nutrients. Generic reference food, not a branded/labeled product. An initial guessed ID (170554) mismatched to chia seeds and was discarded before this correct ID was confirmed.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_pumpkin_seeds_dried',
    nameEn: 'Pumpkin Seeds',
    nameAr: 'بذور اليقطين',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 559,
    protein: 30.2,
    carbs: 10.7,
    fat: 49.1,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170556 (Seeds, pumpkin and squash seed kernels, dried), already per 100g. https://fdc.nal.usda.gov/food-details/170556/nutrients. Generic reference food, not a branded/labeled product.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'nut_chia_seeds_dried',
    nameEn: 'Chia Seeds',
    nameAr: 'بذور شيا',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 486,
    protein: 16.5,
    carbs: 42.1,
    fat: 30.7,
    category: FoodCategory.snack,
    verified: true,
    sourceNote:
        'USDA FoodData Central FDC ID 170554 (Seeds, chia seeds, dried), already per 100g. https://fdc.nal.usda.gov/food-details/170554/nutrients. Generic reference food, not a branded/labeled product. Bonus item discovered while sourcing sunflower seeds (a guessed sunflower ID resolved to this instead) — legitimately sourced, kept as an extra. Not a traditional Libyan ingredient but a common health-food add-in.',
    servingGrams: 100,
  ),

  // ── Eggs (generic, unbranded reference foods; USDA FoodData Central,
  // via myfooddata.com) ── Same convention as Meat/Dairy/Fruit/Vegetable/
  // Nut above: no packaging/barcode/brand, base serving 100g matching
  // USDA's own basis exactly (no scaling math). category:
  // FoodCategory.breakfast — eggs are the first reference batch that maps
  // cleanly onto an existing enum value rather than needing snack/main as
  // a fallback.
  // Unlike the fruit/vegetable/nut batches, this one was NOT accompanied
  // by an "all verified" instruction — the source doc itself is marked
  // DRAFT with every entry verified: false, so that default is kept as-
  // is here rather than assumed overridden.
  // The doc suggests per-single-egg serving weights (raw/boiled ~50g,
  // fried ~46g, scrambled ~61g) instead of 100g, since that is how eggs
  // are actually logged — NOT applied here, since doing so would require
  // scaling the kcal/macro figures off their 100g basis (arithmetic this
  // project avoids doing on the app's behalf); flagging it as a good
  // Phase 4 portion-preset candidate instead.
  // Fried and Scrambled carry real caveats worth reading before treating
  // as exact: Fried assumes a "typical" amount of added cooking fat (real
  // fat/calories vary by how much oil/butter is actually used); Scrambled
  // is USDA's "with milk added" version (protein runs lower and carbs
  // higher than plain egg because of the milk) — worth a clear "milk
  // added" label in the UI so it is not confused with plain cooked egg.
  FoodItem(
    id: 'egg_raw',
    nameEn: 'Egg, Whole (Raw)',
    nameAr: 'بيضة نيئة',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 143,
    protein: 12.6,
    carbs: 0.72,
    fat: 9.5,
    category: FoodCategory.breakfast,
    verified: false,
    sourceNote:
        'USDA FoodData Central FDC ID 171287 (Egg, whole, raw, fresh), per 100g. https://tools.myfooddata.com/nutrition-facts/171287/100g. Generic reference food, not a branded/labeled product. A typical single large raw egg weighs about 50g.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'egg_boiled',
    nameEn: 'Egg, Whole (Boiled)',
    nameAr: 'بيضة مسلوقة',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    category: FoodCategory.breakfast,
    verified: false,
    sourceNote:
        'USDA FoodData Central FDC ID 173424 (Egg, whole, cooked, hard-boiled), per 100g. https://tools.myfooddata.com/nutrition-facts/173424/100g. Generic reference food, not a branded/labeled product. A typical single large hard-boiled egg weighs about 50g.',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'egg_fried',
    nameEn: 'Egg, Whole (Fried)',
    nameAr: 'بيضة مقلية',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 196,
    protein: 13.6,
    carbs: 0.83,
    fat: 14.8,
    category: FoodCategory.breakfast,
    verified: false,
    sourceNote:
        'USDA FoodData Central FDC ID 173423 (Egg, whole, cooked, fried), per 100g. https://tools.myfooddata.com/nutrition-facts/173423/100g. Generic reference food, not a branded/labeled product. This is USDA\'s generic "fried egg" entry — fried in a typical amount of fat (butter/oil); actual fat/calories shift with noticeably more or less oil than that reference method. A typical single large fried egg weighs about 46g (after moisture loss).',
    servingGrams: 100,
  ),
  FoodItem(
    id: 'egg_scrambled',
    nameEn: 'Egg, Whole (Scrambled)',
    nameAr: 'بيضة مخفوقة',
    servingEn: '100 g',
    servingAr: '100 جم',
    kcal: 149,
    protein: 10,
    carbs: 1.6,
    fat: 11,
    category: FoodCategory.breakfast,
    verified: false,
    sourceNote:
        'USDA FoodData Central FDC ID 172187 (Egg, whole, cooked, scrambled), per 100g. https://tools.myfooddata.com/nutrition-facts/172187/100g. Generic reference food, not a branded/labeled product. USDA\'s scrambled-egg entry assumes milk and fat are mixed in during cooking — this is why protein is noticeably lower and carbs higher than the other 3 egg entries. Understates protein / overstates carbs versus plain scrambled egg with no milk added. A scrambled portion from one egg (with milk/butter) weighs about 61g.',
    servingGrams: 100,
  ),
];

final Map<String, FoodItem> foodById = {for (final f in foodDatabase) f.id: f};
