import 'models.dart';

/// ─────────────────────────────────────────────────────────────────────────
/// PLACEHOLDER DATABASE — the real product list was cleared to make room for
/// verified entries entered through the label-photo data pipeline (see
/// CLAUDE.md → DATA PIPELINE). These generic "Sample …" entries exist only
/// so the app has something to show/search/log while that pipeline fills
/// in; every kcal/macro number is a carried-over placeholder estimate, not
/// a real product's value. Replace/extend this list category by category.
/// ─────────────────────────────────────────────────────────────────────────
const List<FoodItem> foodDatabase = [
  // ── Snacks ──
  FoodItem(
    id: 'sample_snack_1',
    nameEn: 'Sample Snack A',
    nameAr: 'وجبة خفيفة تجريبية أ',
    servingEn: '1 pack (25 g)',
    servingAr: 'عبوة (25 جم)',
    kcal: 130,
    protein: 2,
    carbs: 15,
    fat: 7,
    category: FoodCategory.snack,
  ),
  FoodItem(
    id: 'sample_snack_2',
    nameEn: 'Sample Snack B',
    nameAr: 'وجبة خفيفة تجريبية ب',
    servingEn: '1 pack (25 g)',
    servingAr: 'عبوة (25 جم)',
    kcal: 128,
    protein: 1.8,
    carbs: 16,
    fat: 6.5,
    category: FoodCategory.snack,
  ),
  FoodItem(
    id: 'sample_snack_3',
    nameEn: 'Sample Snack C',
    nameAr: 'وجبة خفيفة تجريبية ج',
    servingEn: '1 pack (25 g)',
    servingAr: 'عبوة (25 جم)',
    kcal: 129,
    protein: 1.8,
    carbs: 15.5,
    fat: 6.8,
    category: FoodCategory.snack,
  ),
  FoodItem(
    id: 'sample_snack_4',
    nameEn: 'Sample Snack D',
    nameAr: 'وجبة خفيفة تجريبية د',
    servingEn: '1 pack (20 g)',
    servingAr: 'عبوة (20 جم)',
    kcal: 105,
    protein: 1.5,
    carbs: 12,
    fat: 5.5,
    category: FoodCategory.snack,
  ),

  // ── Mains ──
  FoodItem(
    id: 'sample_main_1',
    nameEn: 'Sample Main Dish A',
    nameAr: 'طبق رئيسي تجريبي أ',
    servingEn: '1 serving (350 g)',
    servingAr: 'حصة (350 جم)',
    kcal: 540,
    protein: 25,
    carbs: 75,
    fat: 15,
    category: FoodCategory.main,
    servingGrams: 350,
    presets: [
      PortionPreset('Modest share', 'حصة صغيرة', 250),
      PortionPreset('Normal share', 'حصة عادية', 350),
      PortionPreset('Generous share', 'حصة كبيرة', 500),
    ],
  ),
  FoodItem(
    id: 'sample_main_2',
    nameEn: 'Sample Main Dish B',
    nameAr: 'طبق رئيسي تجريبي ب',
    servingEn: '1 plate (350 g)',
    servingAr: 'صحن (350 جم)',
    kcal: 550,
    protein: 30,
    carbs: 65,
    fat: 17,
    category: FoodCategory.main,
    servingGrams: 350,
    presets: [
      PortionPreset('Small plate', 'صحن صغير', 250),
      PortionPreset('Plate', 'صحن عادي', 350),
      PortionPreset('Large plate', 'صحن كبير', 500),
    ],
  ),
  FoodItem(
    id: 'sample_main_3',
    nameEn: 'Sample Main Dish C',
    nameAr: 'طبق رئيسي تجريبي ج',
    servingEn: '1 plate (300 g)',
    servingAr: 'صحن (300 جم)',
    kcal: 480,
    protein: 18,
    carbs: 72,
    fat: 12,
    category: FoodCategory.main,
  ),

  // ── Breakfast ──
  FoodItem(
    id: 'sample_breakfast_1',
    nameEn: 'Sample Breakfast A',
    nameAr: 'فطور تجريبي أ',
    servingEn: '1 bowl (200 g)',
    servingAr: 'صحن (200 جم)',
    kcal: 260,
    protein: 14,
    carbs: 34,
    fat: 8,
    category: FoodCategory.breakfast,
    servingGrams: 200,
    presets: [
      PortionPreset('Small bowl', 'صحن صغير', 120),
      PortionPreset('Bowl', 'صحن', 200),
      PortionPreset('Large bowl', 'صحن كبير', 300),
    ],
  ),
  FoodItem(
    id: 'sample_breakfast_2',
    nameEn: 'Sample Breakfast B',
    nameAr: 'فطور تجريبي ب',
    servingEn: '2 pieces',
    servingAr: 'قطعتان',
    kcal: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    category: FoodCategory.breakfast,
  ),
  FoodItem(
    id: 'sample_breakfast_3',
    nameEn: 'Sample Breakfast C',
    nameAr: 'فطور تجريبي ج',
    servingEn: '1 piece (90 g)',
    servingAr: 'قطعة (90 جم)',
    kcal: 240,
    protein: 8,
    carbs: 48,
    fat: 2,
    category: FoodCategory.breakfast,
    servingGrams: 90,
    presets: [
      PortionPreset('Half serving', 'نصف حصة', 45),
      PortionPreset('Serving', 'حصة', 90),
      PortionPreset('Double serving', 'حصتان', 180),
    ],
  ),
  // Zero-fat, zero-protein on purpose — exercises the all-carb edge of the
  // macro-percentage math (kcalPercents).
  FoodItem(
    id: 'sample_breakfast_4',
    nameEn: 'Sample Breakfast D',
    nameAr: 'فطور تجريبي د',
    servingEn: '1 tbsp (21 g)',
    servingAr: 'ملعقة كبيرة (21 جم)',
    kcal: 64,
    protein: 0,
    carbs: 17,
    fat: 0,
    category: FoodCategory.breakfast,
  ),

  // ── Sweets ──
  FoodItem(
    id: 'sample_sweet_1',
    nameEn: 'Sample Sweet A',
    nameAr: 'حلوى تجريبية أ',
    servingEn: '1 piece (50 g)',
    servingAr: 'قطعة (50 جم)',
    kcal: 200,
    protein: 3,
    carbs: 30,
    fat: 8,
    category: FoodCategory.sweet,
  ),

  // ── Drinks ──
  FoodItem(
    id: 'sample_drink_1',
    nameEn: 'Sample Drink A',
    nameAr: 'مشروب تجريبي أ',
    servingEn: '1 cup (240 ml)',
    servingAr: 'كاس (240 مل)',
    kcal: 90,
    protein: 0,
    carbs: 22,
    fat: 0,
    category: FoodCategory.drink,
    isLiquid: true,
  ),

  // ── Dairy / Milk (verified batch, label photos IMG_8120-8216) ──
  // servingGrams treats 1ml as 1g (milk density ~1.0-1.03 g/mL, within
  // label rounding) — every entry's base serving is a 250ml glass.
  // 1 product from the source batch (Al-Sohoul Almond Milk) is held back:
  // its label photo is missing protein/fat entirely (not zero — genuinely
  // absent from the panel), which doesn't fit FoodItem's non-nullable
  // macro fields. Owner said to drop it rather than guess.
  FoodItem(
    id: 'milk_hawaa_full_cream',
    nameEn: 'Hawaa Full Cream Milk (UHT)',
    nameAr: 'حواء - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 148,
    protein: 7.8,
    carbs: 12.0,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 59 kcal, 3.1g protein, 4.8g carb, 3.0g fat (IMG_8120-8122). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241005510161',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_hawaa_fat_free',
    nameEn: 'Hawaa Fat-Free Milk (UHT)',
    nameAr: 'حواء - حليب خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 83,
    protein: 8.3,
    carbs: 12.5,
    fat: 0.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 33 kcal, 3.3g protein, 5.0g carb, 0.2g fat (IMG_8123-8125). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241005510178',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_almarai_full_cream',
    nameEn: 'Almarai Full Cream Milk (UHT)',
    nameAr: 'حليب المراعي كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 146,
    protein: 7.0,
    carbs: 12.3,
    fat: 7.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58.5 kcal, 2.8g protein, 4.9g carb, 3.1g fat (IMG_8126-8128). Label prints per-200ml serving (117 kcal/5.6p/9.8c/6.2f); per-100ml is the owner\'s own halving of that value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6223001874294',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_almarai_fat_free',
    nameEn: 'Almarai Fat-Free Milk (UHT)',
    nameAr: 'حليب المراعي خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 86,
    protein: 7.0,
    carbs: 13.3,
    fat: 0.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 34.5 kcal, 2.8g protein, 5.3g carb, 0.2g fat (IMG_8129-8131). Label prints per-200ml serving (69 kcal/5.6p/10.6c/0.4f); per-100ml is the owner\'s own halving of that value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6223001874300',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_sterilgarda_intero',
    nameEn: 'Sterilgarda Whole Milk (UHT)',
    nameAr: 'حليب ستيريل غاردا كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 163,
    protein: 8.0,
    carbs: 12.3,
    fat: 9.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 65 kcal, 3.2g protein, 4.9g carb, 3.6g fat (IMG_8132-8134). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002795001424',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_sterilgarda_semiskimmed',
    nameEn: 'Sterilgarda Semi-Skimmed Milk (UHT)',
    nameAr: 'حليب ستيريل غاردا نصف الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 118,
    protein: 8.0,
    carbs: 12.5,
    fat: 4.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 47 kcal, 3.2g protein, 5.0g carb, 1.6g fat (IMG_8135-8137). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002795001431',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_nadec_skimmed',
    nameEn: 'Nadec Skimmed Milk (UHT)',
    nameAr: 'حليب نادك خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 80,
    protein: 7.8,
    carbs: 11.8,
    fat: 0.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 32 kcal, 3.1g protein, 4.7g carb, 0.1g fat (IMG_8138-8140). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6281057012015',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_nadec_full_cream',
    nameEn: 'Nadec Full Cream Milk (UHT)',
    nameAr: 'حليب نادك كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 145,
    protein: 7.8,
    carbs: 11.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58 kcal, 3.1g protein, 4.7g carb, 3.0g fat (IMG_8141-8143). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6281057010011',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_granarolo_full_cream',
    nameEn: 'Granarolo Full Cream Milk (UHT)',
    nameAr: 'حليب غرانارولو كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 163,
    protein: 8.0,
    carbs: 12.5,
    fat: 9.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 65 kcal, 3.2g protein, 5.0g carb, 3.6g fat (IMG_8144-8146). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002670169911',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_granarolo_skimmed',
    nameEn: 'Granarolo Skimmed Milk (UHT)',
    nameAr: 'حليب غرانارولو خالي الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 85,
    protein: 8.0,
    carbs: 12.5,
    fat: 0.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 34 kcal, 3.2g protein, 5.0g carb, 0.1g fat (IMG_8147-8149). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8002670162608',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alzahrat_full_cream',
    nameEn: 'Al-Zahrat Full Cream Milk (UHT)',
    nameAr: 'حليب الزهرات كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 159,
    protein: 8.3,
    carbs: 11.8,
    fat: 8.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 63.5 kcal, 3.3g protein, 4.7g carb, 3.5g fat (IMG_8150-8152). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '4100290003937',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_tebra_whole',
    nameEn: 'Tebra Whole Milk (UHT)',
    nameAr: 'حليب تيبرا كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 160,
    protein: 8.0,
    carbs: 12.3,
    fat: 8.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 64 kcal, 3.2g protein, 4.9g carb, 3.5g fat (IMG_8153-8155). Label also prints a native 250ml-serving row (160 kcal/8.0p/12c/8.8f); minor gap vs the x2.5-scaled figures here is the label\'s own rounding. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '7640177012289',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_acacos_full_cream',
    nameEn: 'Acacos Full Cream Milk (reconstituted)',
    nameAr: 'حليب أكاكوس كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 153,
    protein: 8.0,
    carbs: 12.3,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 61 kcal, 3.2g protein, 4.9g carb, 3.0g fat (IMG_8157-8159). Reconstituted from milk powder (water, milk powder, fat, E471, E407/E412), not fresh/UHT like the rest of this batch — shake before serving. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241004250013',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_aljaied_dates',
    nameEn: 'Al-Jaied Dates-Flavored Milk Drink',
    nameAr: 'الجيد - حليب بالتمر',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 180,
    protein: 7.8,
    carbs: 28.3,
    fat: 1.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 72 kcal, 3.1g protein, 11.3g carb, 0.5g fat (prior-session photo). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000911451',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_aljaied_full_cream',
    nameEn: 'Al-Jaied Full Cream Milk',
    nameAr: 'الجيد - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 150,
    protein: 7.8,
    carbs: 12.0,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 60 kcal, 3.1g protein, 4.8g carb, 3.0g fat (prior-session photo). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000910577',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_full_cream_recombined',
    nameEn: 'Al-Naseem Full Cream Milk (Recombined)',
    nameAr: 'النسيم - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 150,
    protein: 7.8,
    carbs: 11.9,
    fat: 7.9,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 60 kcal, 3.13g protein, 4.75g carb, 3.15g fat (IMG_8166-8168). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000044913',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_full_cream_fresh',
    nameEn: 'Al-Naseem Full Cream Milk (Fresh Raw Milk)',
    nameAr: 'النسيم - حليب كامل الدسم (حليب طازج)',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 148,
    protein: 7.8,
    carbs: 13.5,
    fat: 7.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 59 kcal, 3.1g protein, 5.4g carb, 2.8g fat (IMG_8169-8171). Distinct barcode/fat/ingredient source from the Recombined variant above — separate SKU, not a duplicate. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000046979',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_skimmed',
    nameEn: 'Al-Naseem Skimmed Milk',
    nameAr: 'النسيم - حليب منزوع الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 110,
    protein: 7.5,
    carbs: 13.0,
    fat: 1.0,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 44 kcal, 3.0g protein, 5.2g carb, 0.4g fat (IMG_8172-8173). Barcode photo (IMG_8174) is missing from the source Drive folder — left null rather than guessed. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: null, // not captured on the label photo
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_coffee_latte',
    nameEn: 'Al-Naseem Coffee Latte Cream Milk',
    nameAr: 'النسيم - حليب كافي لاتي',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 160,
    protein: 8.8,
    carbs: 12.0,
    fat: 8.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 64 kcal, 3.5g protein, 4.8g carb, 3.5g fat (IMG_8175-8177). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045217',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_chocolate',
    nameEn: 'Al-Naseem Chocolate Milk',
    nameAr: 'النسيم - حليب منكه بالشوكولاتة',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 235,
    protein: 7.5,
    carbs: 33.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 94 kcal, 3.0g protein, 13.5g carb, 3.0g fat (IMG_8178-8180). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045835',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_banana',
    nameEn: 'Al-Naseem Banana-Flavored Milk',
    nameAr: 'النسيم - حليب منكه بالموز',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 218,
    protein: 7.5,
    carbs: 28.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 87 kcal, 3.0g protein, 11.5g carb, 3.0g fat (IMG_8181-8183). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000042308',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_strawberry',
    nameEn: 'Al-Naseem Strawberry-Flavored Milk',
    nameAr: 'النسيم - حليب منكه بالفراولة',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 218,
    protein: 7.5,
    carbs: 28.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 87 kcal, 3.0g protein, 11.5g carb, 3.0g fat (IMG_8184-8186). Nutrition values are identical to the banana variant above — plausible as the same base flavored-milk line, distinct barcode confirms a separate SKU, but not independently re-verified. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045811',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_almond_lowfat',
    nameEn: 'Al-Naseem Almond-Flavored Low-Fat Milk',
    nameAr: 'النسيم - حليب منخفض الدسم بنكهة اللوز',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 170,
    protein: 7.5,
    carbs: 30.0,
    fat: 2.3,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 68 kcal, 3.0g protein, 12.0g carb, 0.9g fat (IMG_8187-8189). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000045804',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_alnaseem_date',
    nameEn: 'Al-Naseem Date Milk',
    nameAr: 'النسيم - حليب بالتمر',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 210,
    protein: 8.0,
    carbs: 26.5,
    fat: 7.8,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 84 kcal, 3.2g protein, 10.6g carb, 3.1g fat (IMG_8190-8192). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000040007',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_elrayhan_full_cream',
    nameEn: 'El Rayhan Full Cream Milk',
    nameAr: 'الريحان - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 158,
    protein: 8.5,
    carbs: 12.0,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 63.35 kcal, 3.4g protein, 4.8g carb, 3.0g fat (IMG_8193-8195). Brand name was initially illegible on the stylized front-panel script; confirmed as El Rayhan (الريحان) by the owner. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000010673',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_safi_full_cream',
    nameEn: 'Safi Full Cream Milk',
    nameAr: 'صافي - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 146,
    protein: 7.5,
    carbs: 12.2,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58.48 kcal, 3.0g protein, 4.87g carb, 3.0g fat (IMG_8196-8198). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241004720844',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_safi_coffee_cream',
    nameEn: 'Safi Coffee Cream Milk',
    nameAr: 'صافي - كريم القهوة',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 146,
    protein: 7.5,
    carbs: 12.2,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 58.48 kcal, 3.0g protein, 4.87g carb, 3.0g fat (IMG_8199-8201). Nutrition panel is digit-for-digit identical to Safi Full Cream Milk despite a distinct barcode — flagged for a manual sanity check against the physical cartons, not independently re-verified. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241004720998',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_teksut_full_cream',
    nameEn: 'Tek Sut Full Cream Milk',
    nameAr: 'تك سوت - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 143,
    protein: 7.3,
    carbs: 11.8,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 57 kcal, 2.9g protein, 4.7g carb, 3.0g fat (IMG_8205-8207). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '8690158120648',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_almazraa_full_cream',
    nameEn: 'Al-Mazraa Full Cream UHT Milk',
    nameAr: 'المزرعة - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 155,
    protein: 9.2,
    carbs: 12.3,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 62.0 kcal, 3.68g protein, 4.9g carb, 3.0g fat (IMG_8208-8210). Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6240000008017',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_judi_full_cream',
    nameEn: 'Judi Full Cream Milk',
    nameAr: 'جودي - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 150,
    protein: 7.8,
    carbs: 12.5,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 60 kcal, 3.1g protein, 5.0g carb, 3.0g fat (IMG_8211-8213). Label prints fat as a minimum (≥3.0g) rather than an exact value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6241000081505',
    servingGrams: 250,
  ),

  FoodItem(
    id: 'milk_juhayna_full_cream',
    nameEn: 'Juhayna Full Cream Milk',
    nameAr: 'جهينة - حليب كامل الدسم',
    servingEn: '1 glass (250 ml)',
    servingAr: 'كأس (250 مل)',
    kcal: 143,
    protein: 7.5,
    carbs: 11.3,
    fat: 7.5,
    category: FoodCategory.drink,
    isLiquid: true,
    verified: true,
    sourceNote:
        'Label states per 100ml: 57 kcal, 3.0g protein, 4.5g carb, 3.0g fat (IMG_8214-8216). Label prints per-200ml serving (114 kcal/6p/9c/6f/230mg calcium); per-100ml is the owner\'s own halving of that value. Scaled ×2.5 to a 250ml serving; verified by owner against label photos.',
    barcode: '6223000350065',
    servingGrams: 250,
  ),
];

final Map<String, FoodItem> foodById = {for (final f in foodDatabase) f.id: f};
